
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gcp-sample
  namespace: argocd
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/gcp
    repoURL: https://github.com/RichGriffin/stack-gcp-sample
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
