apiVersion: servicenetworking.gcp.crossplane.io/v1beta1
kind: Connection
metadata:
  name: connection
spec:
  parent: services/servicenetworking.googleapis.com
  networkRef:
    name: network
  reservedPeeringRangeRefs:
    - name: globaladdress
  reclaimPolicy: Delete
  providerRef:
    name: gcp-provider
