apiVersion: compute.gcp.upbound.io/v1beta1
kind: ExternalVPNGateway
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/externalvpngateway
  labels:
    testing.upbound.io/example-name: external-vpn-gateway
  name: external-vpn-gateway
spec:
  forProvider:
    description: An externally managed VPN gateway
    interface:
      - id: 0
        ipAddress: 8.8.8.8
    redundancyType: SINGLE_IP_INTERNALLY_REDUNDANT