apiVersion: compute.gcp.upbound.io/v1beta1
kind: Firewall
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/firewall
  labels:
    testing.upbound.io/example-name: example_firewall
  name: example-firewall
spec:
  forProvider:
    allow:
      - protocol: icmp
      - ports:
          - "80"
          - "8080"
          - 1000-2000
        protocol: tcp
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: example_firewall_network
    sourceTags:
      - web