apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendService
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/globalforwardingrule
  labels:
    testing.upbound.io/example-name: global-forwarding-rule
  name: global-forwarding-rule
spec:
  forProvider:
    backend:
      - balancingMode: UTILIZATION
        capacityScaler: 1
        groupSelector:
          matchLabels:
            testing.upbound.io/example-name: global-forwarding-rule
        maxUtilization: 1
    healthChecksRefs:
      - name: global-forwarding-rule
    loadBalancingScheme: EXTERNAL
    portName: tcp
    protocol: SSL
    timeoutSec: 10