apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/regionnetworkfirewallpolicyassociation
  labels:
    testing.upbound.io/example-name: basic_network
  name: basic-network
spec:
  forProvider: {}