apiVersion: compute.gcp.upbound.io/v1beta1
kind: NetworkPeering
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/networkpeering
  labels:
    testing.upbound.io/example-name: network-peering
  name: network-peering
spec:
  forProvider:
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: network-peering-1
    peerNetworkSelector:
      matchLabels:
        testing.upbound.io/example-name: network-peering-2