apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Network
metadata:
  name: network
spec:
  forProvider:
    autoCreateSubnetworks: false
    routingConfig:
      routingMode: REGIONAL
  reclaimPolicy: Delete
  providerRef:
    name: gcp-provider
