apiVersion: compute.gcp.upbound.io/v1beta1
kind: NodeGroup
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/nodegroup
  labels:
    testing.upbound.io/example-name: node-group
  name: node-group
spec:
  forProvider:
    description: Example node group
    initialSize: 1
    nodeTemplateSelector:
      matchLabels:
        testing.upbound.io/example-name: node-group
    zone: europe-north1