apiVersion: compute.gcp.upbound.io/v1beta1
kind: Router
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/routernat
  labels:
    testing.upbound.io/example-name: example_routernat_router
  name: example-routernat-router
spec:
  forProvider:
    bgp:
      - asn: 64514
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: example_routernat_network
    region: us-central1