apiVersion: compute.gcp.upbound.io/v1beta1
kind: Router
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/router
  labels:
    testing.upbound.io/example-name: example_router
  name: example-router
spec:
  forProvider:
    bgp:
      - advertiseMode: CUSTOM
        advertisedGroups:
          - ALL_SUBNETS
        advertisedIpRanges:
          - range: 1.2.3.4
          - range: 6.7.0.0/16
        asn: 64514
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: example_router_network
    region: europe-north1