apiVersion: compute.gcp.upbound.io/v1beta1
kind: Subnetwork
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/subnetwork
  labels:
    testing.upbound.io/example-name: example_subnet
  name: example-subnet
spec:
  forProvider:
    ipCidrRange: 10.2.0.0/16
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: example_subnet_network
    region: us-central1
    secondaryIpRange:
      - ipCidrRange: 192.168.10.0/24
        rangeName: test-secondary-range-update1