apiVersion: compute.gcp.upbound.io/v1beta1
kind: BackendService
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/urlmap
  labels:
    testing.upbound.io/example-name: urlmap
  name: urlmap
spec:
  forProvider:
    healthChecksSelector:
      matchLabels:
        testing.upbound.io/example-name: urlmap
    portName: http
    protocol: HTTP
    timeoutSec: 10