---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: minimalgcps.gcp.resourcepacks.crossplane.io
spec:
  group: gcp.resourcepacks.crossplane.io
  names:
    kind: MinimalGCP
    listKind: MinimalGCPList
    plural: minimalgcps
    singular: minimalgcp
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
